// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sigil.proto

package sigilv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SigilAgent_Connect_FullMethodName = "/sigil.v1.SigilAgent/Connect"
	SigilAgent_Ack_FullMethodName     = "/sigil.v1.SigilAgent/Ack"
)

// SigilAgentClient is the client API for SigilAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SigilAgent is the persistent streaming RPC used by Kprobe agents.
type SigilAgentClient interface {
	// Connect opens a server-streaming channel. Sigil pushes certs and policy
	// as they change. The agent calls this once on startup and holds it open.
	Connect(ctx context.Context, in *AgentHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentPush], error)
	// Ack acknowledges receipt of a pushed bundle (for delivery tracking).
	Ack(ctx context.Context, in *AgentAck, opts ...grpc.CallOption) (*AckResponse, error)
}

type sigilAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSigilAgentClient(cc grpc.ClientConnInterface) SigilAgentClient {
	return &sigilAgentClient{cc}
}

func (c *sigilAgentClient) Connect(ctx context.Context, in *AgentHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentPush], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SigilAgent_ServiceDesc.Streams[0], SigilAgent_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentHello, AgentPush]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SigilAgent_ConnectClient = grpc.ServerStreamingClient[AgentPush]

func (c *sigilAgentClient) Ack(ctx context.Context, in *AgentAck, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, SigilAgent_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigilAgentServer is the server API for SigilAgent service.
// All implementations must embed UnimplementedSigilAgentServer
// for forward compatibility.
//
// SigilAgent is the persistent streaming RPC used by Kprobe agents.
type SigilAgentServer interface {
	// Connect opens a server-streaming channel. Sigil pushes certs and policy
	// as they change. The agent calls this once on startup and holds it open.
	Connect(*AgentHello, grpc.ServerStreamingServer[AgentPush]) error
	// Ack acknowledges receipt of a pushed bundle (for delivery tracking).
	Ack(context.Context, *AgentAck) (*AckResponse, error)
	mustEmbedUnimplementedSigilAgentServer()
}

// UnimplementedSigilAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigilAgentServer struct{}

func (UnimplementedSigilAgentServer) Connect(*AgentHello, grpc.ServerStreamingServer[AgentPush]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSigilAgentServer) Ack(context.Context, *AgentAck) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedSigilAgentServer) mustEmbedUnimplementedSigilAgentServer() {}
func (UnimplementedSigilAgentServer) testEmbeddedByValue()                    {}

// UnsafeSigilAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigilAgentServer will
// result in compilation errors.
type UnsafeSigilAgentServer interface {
	mustEmbedUnimplementedSigilAgentServer()
}

func RegisterSigilAgentServer(s grpc.ServiceRegistrar, srv SigilAgentServer) {
	// If the following call panics, it indicates UnimplementedSigilAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SigilAgent_ServiceDesc, srv)
}

func _SigilAgent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentHello)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SigilAgentServer).Connect(m, &grpc.GenericServerStream[AgentHello, AgentPush]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SigilAgent_ConnectServer = grpc.ServerStreamingServer[AgentPush]

func _SigilAgent_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigilAgentServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigilAgent_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigilAgentServer).Ack(ctx, req.(*AgentAck))
	}
	return interceptor(ctx, in, info, handler)
}

// SigilAgent_ServiceDesc is the grpc.ServiceDesc for SigilAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigilAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sigil.v1.SigilAgent",
	HandlerType: (*SigilAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ack",
			Handler:    _SigilAgent_Ack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SigilAgent_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sigil.proto",
}
