// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sigil.proto

package sigilv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertBundle is pushed to a Kprobe agent whenever a cert is issued or rotated.
type CertBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                  // e.g. "service-alpha"
	ServiceCertPem []byte                 `protobuf:"bytes,2,opt,name=service_cert_pem,json=serviceCertPem,proto3" json:"service_cert_pem,omitempty"` // x509 leaf cert in PEM format
	RootCaPem      []byte                 `protobuf:"bytes,3,opt,name=root_ca_pem,json=rootCaPem,proto3" json:"root_ca_pem,omitempty"`                // Sigil root CA cert in PEM format
	ExpiresAtUnix  int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`   // Unix timestamp of leaf cert expiry
	RotateAtUnix   int64                  `protobuf:"varint,5,opt,name=rotate_at_unix,json=rotateAtUnix,proto3" json:"rotate_at_unix,omitempty"`      // Proactive rotation hint (expires_at - 20%)
	KeyPem         []byte                 `protobuf:"bytes,6,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`                           // PKCS#8 private key PEM for the leaf cert
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertBundle) Reset() {
	*x = CertBundle{}
	mi := &file_sigil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertBundle) ProtoMessage() {}

func (x *CertBundle) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertBundle.ProtoReflect.Descriptor instead.
func (*CertBundle) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{0}
}

func (x *CertBundle) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CertBundle) GetServiceCertPem() []byte {
	if x != nil {
		return x.ServiceCertPem
	}
	return nil
}

func (x *CertBundle) GetRootCaPem() []byte {
	if x != nil {
		return x.RootCaPem
	}
	return nil
}

func (x *CertBundle) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *CertBundle) GetRotateAtUnix() int64 {
	if x != nil {
		return x.RotateAtUnix
	}
	return 0
}

func (x *CertBundle) GetKeyPem() []byte {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

// PolicyBundle is pushed to all connected agents on config change.
type PolicyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AllowRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultAllow  bool                   `protobuf:"varint,2,opt,name=default_allow,json=defaultAllow,proto3" json:"default_allow,omitempty"`
	MtlsMode      string                 `protobuf:"bytes,3,opt,name=mtls_mode,json=mtlsMode,proto3" json:"mtls_mode,omitempty"` // "enforce" | "permissive" | "off"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBundle) Reset() {
	*x = PolicyBundle{}
	mi := &file_sigil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundle) ProtoMessage() {}

func (x *PolicyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundle.ProtoReflect.Descriptor instead.
func (*PolicyBundle) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyBundle) GetRules() []*AllowRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PolicyBundle) GetDefaultAllow() bool {
	if x != nil {
		return x.DefaultAllow
	}
	return false
}

func (x *PolicyBundle) GetMtlsMode() string {
	if x != nil {
		return x.MtlsMode
	}
	return ""
}

type AllowRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromService   string                 `protobuf:"bytes,1,opt,name=from_service,json=fromService,proto3" json:"from_service,omitempty"`
	ToServices    []string               `protobuf:"bytes,2,rep,name=to_services,json=toServices,proto3" json:"to_services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRule) Reset() {
	*x = AllowRule{}
	mi := &file_sigil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRule) ProtoMessage() {}

func (x *AllowRule) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRule.ProtoReflect.Descriptor instead.
func (*AllowRule) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{2}
}

func (x *AllowRule) GetFromService() string {
	if x != nil {
		return x.FromService
	}
	return ""
}

func (x *AllowRule) GetToServices() []string {
	if x != nil {
		return x.ToServices
	}
	return nil
}

// AgentHello is the first message sent by a Kprobe agent on connect.
type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	PodServiceIds []string               `protobuf:"bytes,3,rep,name=pod_service_ids,json=podServiceIds,proto3" json:"pod_service_ids,omitempty"` // service IDs currently running on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_sigil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{3}
}

func (x *AgentHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentHello) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AgentHello) GetPodServiceIds() []string {
	if x != nil {
		return x.PodServiceIds
	}
	return nil
}

// AgentPush is streamed from Sigil to the agent.
type AgentPush struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentPush_Cert
	//	*AgentPush_Policy
	Payload       isAgentPush_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPush) Reset() {
	*x = AgentPush{}
	mi := &file_sigil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPush) ProtoMessage() {}

func (x *AgentPush) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPush.ProtoReflect.Descriptor instead.
func (*AgentPush) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{4}
}

func (x *AgentPush) GetPayload() isAgentPush_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentPush) GetCert() *CertBundle {
	if x != nil {
		if x, ok := x.Payload.(*AgentPush_Cert); ok {
			return x.Cert
		}
	}
	return nil
}

func (x *AgentPush) GetPolicy() *PolicyBundle {
	if x != nil {
		if x, ok := x.Payload.(*AgentPush_Policy); ok {
			return x.Policy
		}
	}
	return nil
}

type isAgentPush_Payload interface {
	isAgentPush_Payload()
}

type AgentPush_Cert struct {
	Cert *CertBundle `protobuf:"bytes,1,opt,name=cert,proto3,oneof"`
}

type AgentPush_Policy struct {
	Policy *PolicyBundle `protobuf:"bytes,2,opt,name=policy,proto3,oneof"`
}

func (*AgentPush_Cert) isAgentPush_Payload() {}

func (*AgentPush_Policy) isAgentPush_Payload() {}

// AgentAck acknowledges receipt of a pushed bundle.
type AgentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAck) Reset() {
	*x = AgentAck{}
	mi := &file_sigil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAck) ProtoMessage() {}

func (x *AgentAck) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAck.ProtoReflect.Descriptor instead.
func (*AgentAck) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{5}
}

func (x *AgentAck) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AgentAck) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_sigil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sigil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_sigil_proto_rawDescGZIP(), []int{6}
}

func (x *AckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_sigil_proto protoreflect.FileDescriptor

const file_sigil_proto_rawDesc = "" +
	"\n" +
	"\vsigil.proto\x12\bsigil.v1\"\xdc\x01\n" +
	"\n" +
	"CertBundle\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12(\n" +
	"\x10service_cert_pem\x18\x02 \x01(\fR\x0eserviceCertPem\x12\x1e\n" +
	"\vroot_ca_pem\x18\x03 \x01(\fR\trootCaPem\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\x12$\n" +
	"\x0erotate_at_unix\x18\x05 \x01(\x03R\frotateAtUnix\x12\x17\n" +
	"\akey_pem\x18\x06 \x01(\fR\x06keyPem\"{\n" +
	"\fPolicyBundle\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.sigil.v1.AllowRuleR\x05rules\x12#\n" +
	"\rdefault_allow\x18\x02 \x01(\bR\fdefaultAllow\x12\x1b\n" +
	"\tmtls_mode\x18\x03 \x01(\tR\bmtlsMode\"O\n" +
	"\tAllowRule\x12!\n" +
	"\ffrom_service\x18\x01 \x01(\tR\vfromService\x12\x1f\n" +
	"\vto_services\x18\x02 \x03(\tR\n" +
	"toServices\"l\n" +
	"\n" +
	"AgentHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12&\n" +
	"\x0fpod_service_ids\x18\x03 \x03(\tR\rpodServiceIds\"t\n" +
	"\tAgentPush\x12*\n" +
	"\x04cert\x18\x01 \x01(\v2\x14.sigil.v1.CertBundleH\x00R\x04cert\x120\n" +
	"\x06policy\x18\x02 \x01(\v2\x16.sigil.v1.PolicyBundleH\x00R\x06policyB\t\n" +
	"\apayload\"H\n" +
	"\bAgentAck\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\x03R\n" +
	"receivedAt\"\x1d\n" +
	"\vAckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2x\n" +
	"\n" +
	"SigilAgent\x128\n" +
	"\tSubscribe\x12\x14.sigil.v1.AgentHello\x1a\x13.sigil.v1.AgentPush0\x01\x120\n" +
	"\x03Ack\x12\x12.sigil.v1.AgentAck\x1a\x15.sigil.v1.AckResponseB2Z0github.com/meshlite/sigil/internal/proto;sigilv1b\x06proto3"

var (
	file_sigil_proto_rawDescOnce sync.Once
	file_sigil_proto_rawDescData []byte
)

func file_sigil_proto_rawDescGZIP() []byte {
	file_sigil_proto_rawDescOnce.Do(func() {
		file_sigil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sigil_proto_rawDesc), len(file_sigil_proto_rawDesc)))
	})
	return file_sigil_proto_rawDescData
}

var file_sigil_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sigil_proto_goTypes = []any{
	(*CertBundle)(nil),   // 0: sigil.v1.CertBundle
	(*PolicyBundle)(nil), // 1: sigil.v1.PolicyBundle
	(*AllowRule)(nil),    // 2: sigil.v1.AllowRule
	(*AgentHello)(nil),   // 3: sigil.v1.AgentHello
	(*AgentPush)(nil),    // 4: sigil.v1.AgentPush
	(*AgentAck)(nil),     // 5: sigil.v1.AgentAck
	(*AckResponse)(nil),  // 6: sigil.v1.AckResponse
}
var file_sigil_proto_depIdxs = []int32{
	2, // 0: sigil.v1.PolicyBundle.rules:type_name -> sigil.v1.AllowRule
	0, // 1: sigil.v1.AgentPush.cert:type_name -> sigil.v1.CertBundle
	1, // 2: sigil.v1.AgentPush.policy:type_name -> sigil.v1.PolicyBundle
	3, // 3: sigil.v1.SigilAgent.Subscribe:input_type -> sigil.v1.AgentHello
	5, // 4: sigil.v1.SigilAgent.Ack:input_type -> sigil.v1.AgentAck
	4, // 5: sigil.v1.SigilAgent.Subscribe:output_type -> sigil.v1.AgentPush
	6, // 6: sigil.v1.SigilAgent.Ack:output_type -> sigil.v1.AckResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sigil_proto_init() }
func file_sigil_proto_init() {
	if File_sigil_proto != nil {
		return
	}
	file_sigil_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentPush_Cert)(nil),
		(*AgentPush_Policy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sigil_proto_rawDesc), len(file_sigil_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sigil_proto_goTypes,
		DependencyIndexes: file_sigil_proto_depIdxs,
		MessageInfos:      file_sigil_proto_msgTypes,
	}.Build()
	File_sigil_proto = out.File
	file_sigil_proto_goTypes = nil
	file_sigil_proto_depIdxs = nil
}
