replicaCount: 1

image:
  repository: ghcr.io/andrew-william-dev/meshlite/trace
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  httpPort: 3000
  metricsPort: 9090

resources: {}

trace:
  httpAddr: ":3000"
  metricsAddr: ":9090"

ingress:
  enabled: false
  className: ""
  annotations:
    # alb.ingress.kubernetes.io/scheme: internal
    # alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: trace.mesh.internal
      paths:
        - path: /
          pathType: Prefix
  tls: []
