image:
  repository: meshlite/kprobe
  pullPolicy: IfNotPresent
  tag: "phase3"

sigil:
  addr: "sigil.meshlite-system.svc.cluster.local:8443"

trace:
  addr: "http://trace.meshlite-system.svc.cluster.local:3000"

cluster:
  id: "dev"

ebpf:
  iface: "eth0"
  path: "/app/kprobe-ebpf"
